Create footer in project
20210502-FE/tech_store pull request #1
Opened 2021-08-02 11:01 UTC by VovaDoronin

2021-08-02 11:08 UTC, VovaDoronin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Footer block](https://trello.com/c/nGUnVXjC/6-footer-block)

2021-08-03 09:49 UTC, JuliaSavych requested changes

2021-08-03 09:49 UTC, JuliaSavych commented on dev/js/main.js
> +const firstButton = document.getElementsByClassName('footer__button-arrow')[0];
не універсальний спосіб) сьогодні на занятті розберемо всі помилки

2021-08-03 09:49 UTC, JuliaSavych commented on dev/pug/blocks/footer.pug
> +-
![Screenshot from 2021-08-03 12-46-07](https://user-images.githubusercontent.com/19241160/127995259-823af61f-1b7a-4beb-a2b9-aaa2e62eb22e.png)

2021-08-06 18:45 UTC, JuliaSavych approved these changes

2021-08-06 18:45 UTC, merged